export default [
    {
        name:                   'light',
        '--primary':            '#0b88e8',
        '--primary-light':      '#49abf6',
        '--accent':             '#aa66ff',
        '--background':         '#fff',
        '--background-dark':    '#f6f6f6',
        '--background-darkest': '#e9e9e9',
        '--font-light':         '#fff',
        '--font-dark':          '#232323',
        '--font-contrast':      '#fff',
        '--white':              '#fff',
        '--grey':               '#f2f2f2',
        '--black':              '#000',
    },
    {
        name:                   'dark',
        '--primary':            '#f2da9b',
        '--primary-light':      '#ffb65e',
        '--accent':             '#eeffad',
        '--background':         '#333',
        '--background-dark':    '#212121',
        '--background-darkest': '#191919',
        '--font-light':         '#141414',
        '--font-dark':          '#888',
        '--font-contrast':      '#333',
        '--white':              '#fff',
        '--grey':               '#f2f2f2',
        '--black':              '#000',
    },
];
